TimeSheetApp/Models/TimeSheet.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TimeSheetApp.Models
{
    public class TimeSheet
    {
        [Key]
        public int Id { get; set; }
        public string Username { get; set; }
        public DateTime Day { get; set; } = DateTime.Now;
        public TimeSpan ElapsedTime { get; set; }
        public  IEnumerable<ClockInClockOutTime> ClockInClockOutTimes { get; set; }
    }
}

TimeSheetApp/Controllers/TimeSheetController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using TimeSheetApp.Models;
using TimeSheetApp.Models.ViewModel;
using TimeSheetApp.Services.IServices;

namespace TimeSheetApp.Controllers
{
    public class TimeSheetController : Controller
    {
        private readonly ITimeSheetService _timeSheetService;
        private  Stopwatch timer = new Stopwatch();
        private bool clockedIn;
        
       
        public TimeSheetController(ITimeSheetService timeSheetService)
        {
            _timeSheetService = timeSheetService;
        }

        public IActionResult Panel(string username)
        {
            byte[] check;
             HttpContext.Session.TryGetValue("ssrunning",out check); 
            if(check is null)
            {
                HttpContext.Session.SetString("ssrunning", "false");
            }
            
            MyModel model = new MyModel { Username = username };
            return View(model);
        }
        
        [HttpPost]
        public async Task<IActionResult> ClockIn(MyModel model)
        {
            clockedIn = bool.Parse(HttpContext.Session.GetString("ssrunning"));
            var sheet = await _timeSheetService.GetLastTimeSheet(model.Username);
            var clockInTime = new ClockInClockOutTime { ClockInTime = DateTime.Now, Reason = model.Reason };

            if (!clockedIn)
            {
                

                if (sheet!= null && DateTime.Now.Date == sheet.Day.Date)
                {
                    timer.Start();
                    List<ClockInClockOutTime> AllClockInClockOutTimes = sheet.ClockInClockOutTimes.ToList();
                    AllClockInClockOutTimes.Add(clockInTime);
                    sheet.ElapsedTime = timer.Elapsed;
                    sheet.ClockInClockOutTimes = AllClockInClockOutTimes;
                    var updatedSheet = await _timeSheetService.Update(sheet.Id, sheet);
                    HttpContext.Session.SetString("ssrunning", "true");
                    return RedirectToAction("Dashboard", "Home", new { id = updatedSheet.Username });
                    
                }
                else if (sheet==null || DateTime.Now.Date > sheet.Day.Date)
                {
                    timer.Restart();
                    var newsheet = new TimeSheet { Username = model.Username, ElapsedTime = timer.Elapsed, Day = DateTime.Now, ClockInClockOutTimes = new List<ClockInClockOutTime>() { new ClockInClockOutTime { ClockInTime = DateTime.Now, Reason = model.Reason } } };
                    var addedsheet = await _timeSheetService.Create(newsheet);
                    HttpContext.Session.SetString("ssrunning", "true");
                    return RedirectToAction("Dashboard", "Home", new{id = addedsheet.Username});

                }
                else
                {
                    return RedirectToAction("Dashboard", "Home", new { id =sheet.Username });
                }

            }
            else
            {
                string message = "You are clocked in, Please clock out first";
                return View("Panel", new MyModel { Message = message });

            }
            
        }
        [HttpPost]
        public async Task<IActionResult> ClockOut(MyModel model)
        {
            clockedIn = bool.Parse(HttpContext.Session.GetString("ssrunning"));
            var sheet = await _timeSheetService.GetLastTimeSheet(model.Username);
            var clockOutTime = new ClockInClockOutTime { ClockOutTime = DateTime.Now, Reason = model.Reason };
            if (clockedIn) 
            {
                
                
            timer.Stop();
            if (DateTime.Now.Date == sheet.Day.Date)
            {
                
                List<ClockInClockOutTime> AllClockInClockOutTimes = sheet.ClockInClockOutTimes.ToList();
                sheet.ElapsedTime = timer.Elapsed;
                  AllClockInClockOutTimes.Add(clockOutTime);
                    sheet.ClockInClockOutTimes = AllClockInClockOutTimes;
                var updatedSheet = await _timeSheetService.Update(sheet.Id, sheet);
                    HttpContext.Session.SetString("ssrunning", "false");
                    return RedirectToAction("Dashboard", "Home",new { id = updatedSheet.Username });
            }
            else if (DateTime.Now.Date > sheet.Day.Date)
            {
                var newsheet = new TimeSheet { Username = model.Username, ElapsedTime = timer.Elapsed, Day = DateTime.Now, ClockInClockOutTimes = new List<ClockInClockOutTime>() { new ClockInClockOutTime { ClockOutTime = DateTime.Now, Reason = model.Reason } } };
                var addedsheet = await _timeSheetService.Create(newsheet);
                    HttpContext.Session.SetString("ssrunning", "false");
                    return RedirectToAction("Dashboard", "Home", new { id = addedsheet.Username });
            }
            else
            {
                return RedirectToAction("Dashboard", "Home", new { id = sheet.Username});
            }
            }
            else
            {
                string message = "You are still clocked out, Please clock in first";
                return View("Panel", new MyModel { Message = message});
            }
            
        }
    }
}

TimeSheetApp/Views/TimeSheet/Panel.cshtml
@model TimeSheetApp.Models.ViewModel.MyModel
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor




<div class="clocklook">
    <div class="digitalcontainer">
        <div class="clock-container">
            <div class="hours">
                <span>Hours</span>
                <p id='hour'> 00 </p>
            </div>
            <div class="colon"></div>
            <div class="minutes">
                <span>Minutes</span>
                <p id='minute'> 00 </p>
            </div>
            <div class="colon"></div>
            <div class="seconds">
                <span>Seconds</span>
                <p id='second'> 00 </p>
            </div>
        </div>
        <div class="bottom">
            <div class="progress-bar" id="progress"></div>
        </div>
    </div>




</div>
<div class="">


    <div class="row w-75 mx-auto">
        <div class="col-6">
            <form asp-action="ClockIn" asp-controller="TimeSheet">
                <div asp-validation-summary="All"></div>
                <button type="submit" class="w-25  mx-4 mb-2 btn btn-primary btn-block border rounded-circle" style="height:100px"> Clock In</button>
                <input type="text" placeholder="Reason" asp-for="@Model.Username" class="d-none" />
                <input required type="text" placeholder="Reason" asp-for="@Model.Reason" />
            </form>

        </div>

        <div class="col-6">
            <form asp-action="ClockOut" asp-controller="TimeSheet">
                <input type="text" placeholder="Reason" asp-for="@Model.Username" class="d-none" />
                <button type="submit" class="w-25  mt-4 mx-4 mb-2 btn btn-danger btn-block border rounded-circle" style="height:100px">ClockOut</button>
                <input required type="text" placeholder="Reason" asp-for="@Model.Reason" />
            </form>
        </div>

    </div>
</div>







@if (Model.Message is not null)
{
    <script type="text/javascript">
                    window.onload = function () {
                        alert("@Model.Message")
                    }
    </script>
}
<script src="~/js/app.js"></script>
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}